name: 'Determine Version Bump Action'
author: 'Joshua Clements'
description: 'Determine the version bump required and the next applicable version'
inputs:
  currentVersion:
    description: 'Current package version'
    required: true
outputs:
  versionBump:
    description: 'The type of bump (major, minor, patch)'
  bumpedVersion:
    description: 'The bumped version'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'git-commit'
  color: 'purple'
